vim.opt.relativenumber = true 
vim.opt.number = true 
vim.opt.cmdheight = 2 
vim.opt.ignorecase = true 
vim.opt.smartcase = true 
vim.opt.pumheight = 10 
vim.opt.showmode = false
vim.opt.tabstop = 2
vim.opt.wrap = false
--vim.opt.termguicolors = true  
vim.opt.splitbelow = true
vim.opt.splitright = true 
vim.opt.fileencoding = "utf-8"
vim.opt.smartindent = true
vim.opt.shiftwidth = 2
vim.opt.timeoutlen = 1000 
vim.opt.mouse = "a" 
vim.opt.undofile = true 
vim.opt.title = true
vim.opt.hlsearch = true 
vim.opt.completeopt = {menuone, preview}

