require "user.keymaps"
require "user.options"
require "user.nvim-tree"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.masonConfig"
require "user.null_ls"
require "user.lsp"
require "user.autopairs"
-- require "user.nvim-tree"
require "user.comment"
require "user.telescope"
require "user.formatter"
require "user.harpoon"
require "user.treesitter"

